version: "3"
services:
  web:
    build: "./web"
    ports:
      - "3000:3000"
  auth:
    build: "./auth"
    ports:
      - "3001:3000"
  nginx:
    image: nginx:1.17.10
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - web
